runtime: python312

entrypoint: gunicorn -b :$PORT app:app

# service: default
# service: test
# instance_class: F2
# automatic_scaling:
#   min_instances: 5
#   max_instances: 10
#   target_cpu_utilization: 0.65
#   target_throughput_utilization: 0.65
#   max_concurrent_requests: 80
#   min_pending_latency: 30ms
#   max_pending_latency: automatic

handlers:
  - url: /.*
    script: auto

